#**Tugas Praktikum Natural Language Processing**

#**Nama : Gavrilla Claudia**

#**NIM : 21110004**

#**Kelas : S1SD02A**

In [4]:
pip install regex matplotlib sastrawi xlsxwriter nltk

In [5]:
#import modul
import pandas as pd
import numpy as np
import re as reg
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
data = pd.read_csv('Jungkook.csv')
data

Unnamed: 0                      created_at               id_str  \
0             0  Wed Oct 04 03:23:42 +0000 2023  1709408926565826963   
1             1  Wed Oct 04 03:23:42 +0000 2023  1709408926435889254   
2             2  Wed Oct 04 03:23:40 +0000 2023  1709408921524281824   
3             3  Wed Oct 04 03:23:40 +0000 2023  1709408921104908629   
4             4  Wed Oct 04 03:23:40 +0000 2023  1709408920123683144   
..          ...                             ...                  ...   
712         712  Wed Oct 04 03:15:40 +0000 2023  1709406906966577280   
713         713  Wed Oct 04 03:15:40 +0000 2023  1709406905230373215   
714         714  Wed Oct 04 03:15:39 +0000 2023  1709406903237743058   
715         715  Wed Oct 04 03:15:39 +0000 2023  1709406903141642430   
716         716  Wed Oct 04 03:15:38 +0000 2023  1709406899706450075   

                                             full_text  quote_count  \
0                                  #JungKook_GOLDEN 👇👇            0   
1    This announcement doesn’t say anything about a...            0   
2    Inspired by the golden moments of #JungKook, h...            0   
3    Inspired by the golden moments of #JungKook, h...            0   
4    방탄소년단 방탄 버터 가디건 포카 양도 bts butter cardigan mini...            0   
..                                                 ...          ...   
712  Noturnas CHARTMYS  no SPF x3 e na AM rodando, ...            0   
713  Jungkook GOLEDN album unopen sealed sell  정국 골...            0   
714  LISTOO TAEHYUNG LE HACE EL WATER CHALLENGE A J...            0   
715                            jungkook bobo keknya yh            0   
716  Is There Such A Thing As Original Asian Sound?...            0   

     reply_count  retweet_count  favorite_count lang          user_id_str  \
0              0              0               0  qme  1674311398770331649   
1              0              0               0   en            346247756   
2              0              0               0   en  1146317892352393216   
3              0              0               0   en  1587683842625781760   
4              0              0               0   ko  1310575995296968706   
..           ...            ...             ...  ...                  ...   
712            0              2               3   pt  1585335558028640283   
713            0              0               0   ko  1051382608053993472   
714            0              0               0   en  1492986337653366791   
715            0              0               0   in  1389477371506434048   
716            0              0               0   en  1406411208295518209   

     conversation_id_str      username  \
0    1709408926565826963     racesar86   
1    1709408926435889254   laurayjames   
2    1709408921524281824  Min_myyoongi   
3    1709408921104908629     Andythv16   
4    1709408920123683144       _derfun   
..                   ...           ...   
712  1709406906966577280     mony7play   
713  1709406905230373215  bts_pocasell   
714  1709406903237743058      kthvxguk   
715  1709406903141642430     zeekoochi   
716  1709406899706450075      jctwits1   

                                             tweet_url  
0    https://twitter.com/racesar86/status/170940892...  
1    https://twitter.com/laurayjames/status/1709408...  
2    https://twitter.com/Min_myyoongi/status/170940...  
3    https://twitter.com/Andythv16/status/170940892...  
4    https://twitter.com/_derfun/status/17094089201...  
..                                                 ...  
712  https://twitter.com/mony7play/status/170940690...  
713  https://twitter.com/bts_pocasell/status/170940...  
714  https://twitter.com/kthvxguk/status/1709406903...  
715  https://twitter.com/zeekoochi/status/170940690...  
716  https://twitter.com/jctwits1/status/1709406899...  

[717 rows x 13 columns]

In [7]:
#Preprocessing
import re as reg
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

slangs={'yg':'yang', 'tdk':'tidak', 'pd':'pada', 'mlh':'malah', 'jgn':'jangan', 'jg':'juga', 'tp':'tapi', 'blkg': 'belakang', 'dr':'dari', 'klo':'kalo', 'lg':'lagi', 'btw':'buat',
        'dlm':'dalam','dgn':'dengan', 'poto':'foto', 'g':'tidak', 'n':'dan', 'ad':'ada', 'brp': 'berapa', "abis": "habis", "ad": "ada", "adlh": "adalah", "afaik": "as far as i know",
        "ahaha": "haha", "aj": "saja", "ajep-ajep": "dunia gemerlap", "ak": "saya", "akika": "aku", "akkoh": "aku", "akuwh": "aku", "alay": "norak", "alow": "halo", "ambilin": "ambilkan",
        "ancur": "hancur", "anjrit": "anjing", "anter": "antar", "ap2": "apa-apa", "apasih": "apa sih", "apes": "sial", "aps": "apa", "aq": "saya", "aquwh": "aku", "asbun": "asal bunyi",
        "aseekk": "asyik", "asekk": "asyik", "asem": "asam", "aspal": "asli tetapi palsu", "astul": "asal tulis", "ato": "atau", "au ah": "tidak mau tahu", "awak": "saya", "ay": "sayang",
        "ayank": "sayang", "b4": "sebelum", "bakalan": "akan", "bandes": "bantuan desa", "bangedh": "banget", "banpol": "bantuan polisi", "banpur": "bantuan tempur", "basbang": "basi",
        "bcanda": "bercanda", "bdg": "bandung", "begajulan": "nakal", "beliin": "belikan", "bencong": "banci", "bentar": "sebentar", "ber3": "bertiga", "beresin": "membereskan", "bete":
        "bosan", "beud": "banget", "bg": "abang", "bgmn": "bagaimana", "bgt": "banget", "bijimane": "bagaimana", "bintal": "bimbingan mental", "bkl": "akan", "bknnya": "bukannya",
        "blegug": "bodoh", "blh": "boleh", "bln": "bulan", "blum": "belum", "bnci": "benci", "bnran": "yang benar", "bodor": "lucu", "bokap": "ayah", "boker": "buang air besar", "bokis":
        "bohong", "boljug": "boleh juga", "bonek": "bocah nekat", "boyeh": "boleh", "br": "baru", "brg": "bareng", "bro": "saudara laki-laki", "bru": "baru", "bs": "bisa", "bsen": "bosan",
        "bt": "buat", "btw": "ngomong-ngomong", "buaya": "tidak setia", "bubbu": "tidur", "bubu": "tidur", "bumil": "ibu hamil", "bw": "bawa", "bwt": "buat", "byk": "banyak", "byrin": "bayarkan",
        "cabal": "sabar", "cadas": "keren", "calo": "makelar", "can": "belum", "capcus": "pergi", "caper": "cari perhatian", "ce": "cewek", "cekal": "cegah tangkal", "cemen": "penakut",
        "cengengesan": "tertawa", "cepet": "cepat", "cew": "cewek", "chuyunk": "sayang", "cimeng": "ganja", "cipika cipiki": "cium pipi kanan cium pipi kiri", "ciyh": "sih", "ckepp": "cakep",
        "ckp": "cakep", "cmiiw": "correct me if i'm wrong", "cmpur": "campur", "cong": "banci", "conlok": "cinta lokasi", "cowwyy": "maaf", "cp": "siapa", "cpe": "capek", "cppe": "capek",
        "cucok": "cocok", "cuex": "cuek", "cumi": "Cuma miscall", "cups": "culun", "curanmor": "pencurian kendaraan bermotor", "curcol": "curahan hati colongan", "cwek": "cewek", "cyin": "cinta",
        "d": "di", "dah": "deh", "dapet": "dapat", "de": "adik", "dek": "adik", "demen": "suka", "deyh": "deh", "dgn": "dengan", "diancurin": "dihancurkan", "dimaafin": "dimaafkan",
        "dimintak": "diminta", "disono": "di sana", "dket": "dekat", "dkk": "dan kawan-kawan", "dll": "dan lain-lain", "dlu": "dulu", "dngn": "dengan", "dodol": "bodoh", "doku": "uang",
        "dongs": "dong", "dpt": "dapat", "dri": "dari", "drmn": "darimana", "drtd": "dari tadi", "dst": "dan seterusnya", "dtg": "datang", "duh": "aduh", "duren": "durian", "ed": "edisi",
        "egp": "emang gue pikirin", "eke": "aku", "elu": "kamu", "emangnya": "memangnya", "emng": "memang", "endak": "tidak", "enggak": "tidak", "envy": "iri", "ex": "mantan", "fax": "facsimile",
        "fifo": "first in first out", "folbek": "follow back", "fyi": "sebagai informasi", "gaada": "tidak ada uang", "gag": "tidak", "gaje": "tidak jelas", "gak papa": "tidak apa-apa",
        "gan": "juragan", "gaptek": "gagap teknologi", "gatek": "gagap teknologi", "gawe": "kerja", "gbs": "tidak bisa", "gebetan": "orang yang disuka", "geje": "tidak jelas",
        "gepeng": "gelandangan dan pengemis", "ghiy": "lagi", "gile": "gila", "gimana": "bagaimana", "gino": "gigi nongol", "githu": "gitu", "gj": "tidak jelas", "gmana": "bagaimana",
        "gn": "begini", "goblok": "bodoh", "golput": "golongan putih", "gowes": "mengayuh sepeda", "gpny": "tidak punya", "gr": "gede rasa", "gretongan": "gratisan", "gtau": "tidak tahu",
        "gua": "saya", "guoblok": "goblok", "gw": "saya", "ha": "tertawa", "haha": "tertawa", "hallow": "halo", "hankam": "pertahanan dan keamanan", "hehe": "he", "helo": "halo", "hey": "hai",
        "hlm": "halaman", "hny": "hanya", "hoax": "isu bohong", "hr": "hari", "hrus": "harus", "hubdar": "perhubungan darat", "huff": "mengeluh", "hum": "rumah", "humz": "rumah", "ilang": "hilang",
        "ilfil": "tidak suka", "imho": "in my humble opinion", "imoetz": "imut", "item": "hitam", "itungan": "hitungan", "iye": "iya", "ja": "saja", "jadiin": "jadi", "jaim": "jaga image",
        "jayus": "tidak lucu", "jdi": "jadi", "jem": "jam", "jga": "juga", "jgnkan": "jangankan", "jir": "anjing", "jln": "jalan", "jomblo": "tidak punya pacar", "jubir": "juru bicara",
        "jutek": "galak", "k": "ke", "kab": "kabupaten", "kabor": "kabur", "kacrut": "kacau", "kadiv": "kepala divisi", "kagak": "tidak", "kalo": "kalau", "kampret": "sialan",
        "kamtibmas": "keamanan dan ketertiban masyarakat", "kamuwh": "kamu", "kanwil": "kantor wilayah", "karna": "karena", "kasubbag": "kepala subbagian", "katrok": "kampungan",
        "kayanya": "kayaknya", "kbr": "kabar", "kdu": "harus", "kec": "kecamatan", "kejurnas": "kejuaraan nasional", "kekeuh": "keras kepala", "kel": "kelurahan", "kemaren": "kemarin",
        "kepengen": "mau", "kepingin": "mau", "kepsek": "kepala sekolah", "kesbang": "kesatuan bangsa", "kesra": "kesejahteraan rakyat", "ketrima": "diterima", "kgiatan": "kegiatan",
        "kibul": "bohong", "kimpoi": "kawin", "kl": "kalau", "klianz": "kalian", "kloter": "kelompok terbang", "klw": "kalau", "km": "kamu", "kmps": "kampus", "kmrn": "kemarin", "knal": "kenal",
        "knp": "kenapa", "kodya": "kota madya", "komdis": "komisi disiplin", "komsov": "komunis sovyet", "kongkow": "kumpul bareng teman-teman", "kopdar": "kopi darat", "korup": "korupsi",
        "kpn": "kapan", "krenz": "keren", "krm": "kirim", "kt": "kita", "ktmu": "ketemu", "ktr": "kantor", "kuper": "kurang pergaulan", "kw": "imitasi", "kyk": "seperti", "la": "lah",
        "lam": "salam", "lamp": "lampiran", "lanud": "landasan udara", "latgab": "latihan gabungan", "lebay": "berlebihan", "leh": "boleh", "lelet": "lambat", "lemot": "lambat", "lgi": "lagi",
        "lgsg": "langsung", "liat": "lihat", "litbang": "penelitian dan pengembangan", "lmyn": "lumayan", "lo": "kamu", "loe": "kamu", "lola": "lambat berfikir", "louph": "cinta", "low": "kalau",
        "lp": "lupa", "luber": "langsung, umum, bebas, dan rahasia", "luchuw": "lucu", "lum": "belum", "luthu": "lucu", "lwn": "lawan", "maacih": "terima kasih", "mabal": "bolos", "macem": "macam", "macih": "masih", "maem": "makan", "magabut": "makan gaji buta", "maho": "homo", "mak jang": "kaget", "maksain": "memaksa", "malem": "malam", "mam": "makan", "maneh": "kamu", "maniez": "manis", "mao": "mau", "masukin": "masukkan", "melu": "ikut", "mepet": "dekat sekali", "mgu": "minggu", "migas": "minyak dan gas bumi", "mikol": "minuman beralkohol", "miras": "minuman keras", "mlah": "malah", "mngkn": "mungkin", "mo": "mau", "mokad": "mati", "moso": "masa", "mpe": "sampai", "msk": "masuk", "mslh": "masalah", "mt": "makan teman", "mubes": "musyawarah besar", "mulu": "melulu", "mumpung": "selagi", "munas": "musyawarah nasional", "muntaber": "muntah dan berak", "musti": "mesti", "muupz": "maaf", "mw": "now watching", "n": "dan", "nanam": "menanam", "nanya": "bertanya", "napa": "kenapa", "napi": "narapidana", "napza": "narkotika, alkohol, psikotropika, dan zat adiktif ", "narkoba": "narkotika, psikotropika, dan obat terlarang", "nasgor": "nasi goreng", "nda": "tidak", "ndiri": "sendiri", "ne": "ini", "nekolin": "neokolonialisme", "nembak": "menyatakan cinta", "ngabuburit": "menunggu berbuka puasa", "ngaku": "mengaku", "ngambil": "mengambil", "nganggur": "tidak punya pekerjaan", "ngapah": "kenapa", "ngaret": "terlambat", "ngasih": "memberikan", "ngebandel": "berbuat bandel", "ngegosip": "bergosip", "ngeklaim": "mengklaim", "ngeksis": "menjadi eksis", "ngeles": "berkilah", "ngelidur": "menggigau", "ngerampok": "merampok", "ngga": "tidak", "ngibul": "berbohong", "ngiler": "mau", "ngiri": "iri", "ngisiin": "mengisikan", "ngmng": "bicara", "ngomong": "bicara", "ngubek2": "mencari-cari", "ngurus": "mengurus", "nie": "ini", "nih": "ini", "niyh": "nih", "nmr": "nomor", "nntn": "nonton", "nobar": "nonton bareng", "np": "now playing", "ntar": "nanti", "ntn": "nonton", "numpuk": "bertumpuk", "nutupin": "menutupi", "nyari": "mencari", "nyekar": "menyekar", "nyicil": "mencicil", "nyoblos": "mencoblos", "nyokap": "ibu", "ogah": "tidak mau", "ol": "online", "ongkir": "ongkos kirim", "oot": "out of topic", "org2": "orang-orang", "ortu": "orang tua", "otda": "otonomi daerah", "otw": "on the way, sedang di jalan", "pacal": "pacar", "pake": "pakai", "pala": "kepala", "pansus": "panitia khusus", "parpol": "partai politik", "pasutri": "pasangan suami istri", "pd": "pada", "pede": "percaya diri", "pelatnas": "pemusatan latihan nasional", "pemda": "pemerintah daerah", "pemkot": "pemerintah kota", "pemred": "pemimpin redaksi", "penjas": "pendidikan jasmani", "perda": "peraturan daerah", "perhatiin": "perhatikan", "pesenan": "pesanan", "pgang": "pegang", "pi": "tapi", "pilkada": "pemilihan kepala daerah", "pisan": "sangat", "pk": "penjahat kelamin", "plg": "paling", "pmrnth": "pemerintah", "polantas": "polisi lalu lintas", "ponpes": "pondok pesantren", "pp": "pulang pergi", "prg": "pergi", "prnh": "pernah", "psen": "pesan", "pst": "pasti", "pswt": "pesawat", "pw": "posisi nyaman", "qmu": "kamu", "rakor": "rapat koordinasi", "ranmor": "kendaraan bermotor", "re": "reply", "ref": "referensi", "rehab": "rehabilitasi", "rempong": "sulit", "repp": "balas", "restik": "reserse narkotika", "rhs": "rahasia", "rmh": "rumah", "ru": "baru", "ruko": "rumah toko", "rusunawa": "rumah susun sewa", "ruz": "terus", "saia": "saya", "salting": "salah tingkah", "sampe": "sampai", "samsek": "sama sekali", "sapose": "siapa", "satpam": "satuan pengamanan", "sbb": "sebagai berikut", "sbh": "sebuah", "sbnrny": "sebenarnya", "scr": "secara", "sdgkn": "sedangkan", "sdkt": "sedikit", "se7": "setuju", "sebelas dua belas": "mirip", "sembako": "sembilan bahan pokok", "sempet": "sempat", "sendratari": "seni drama tari", "sgt": "sangat", "shg": "sehingga", "siech": "sih", "sikon": "situasi dan kondisi", "sinetron": "sinema elektronik", "siramin": "siramkan", "sj": "saja", "skalian": "sekalian", "sklh": "sekolah", "skt": "sakit", "slesai": "selesai", "sll": "selalu", "slma": "selama", "slsai": "selesai", "smpt": "sempat", "smw": "semua", "sndiri": "sendiri", "soljum": "sholat jumat", "songong": "sombong", "sory": "maaf", "sosek": "sosial-ekonomi", "sotoy": "sok tahu", "spa": "siapa", "sppa": "siapa", "spt": "seperti", "srtfkt": "sertifikat", "stiap": "setiap", "stlh": "setelah", "suk": "masuk", "sumpek": "sempit", "syg": "sayang", "t4": "tempat", "tajir": "kaya", "tau": "tahu", "taw": "tahu", "td": "tadi", "tdk": "tidak", "teh": "kakak perempuan", "telat": "terlambat", "telmi": "telat berpikir", "temen": "teman", "tengil": "menyebalkan", "tepar": "terkapar", "tggu": "tunggu", "tgu": "tunggu", "thankz": "terima kasih", "thn": "tahun", "tilang": "bukti pelanggaran", "tipiwan": "TvOne", "tks": "terima kasih", "tlp": "telepon", "tls": "tulis", "tmbah": "tambah", "tmen2": "teman-teman", "tmpah": "tumpah", "tmpt": "tempat", "tngu": "tunggu", "tnyta": "ternyata", "tokai": "tai", "toserba": "toko serba ada", "tpi": "tapi", "trdhulu": "terdahulu", "trima": "terima kasih", "trm": "terima", "trs": "terus", "trutama": "terutama", "ts": "penulis", "tst": "tahu sama tahu", "ttg": "tentang", "tuch": "tuh", "tuir": "tua", "tw": "tahu", "u": "kamu", "ud": "sudah", "udah": "sudah", "ujg": "ujung", "ul": "ulangan", "unyu": "lucu", "uplot": "unggah", "urang": "saya", "usah": "perlu", "utk": "untuk", "valas": "valuta asing", "w/": "dengan", "wadir": "wakil direktur", "wamil": "wajib militer", "warkop": "warung kopi", "warteg": "warung tegal", "wat": "buat", "wkt": "waktu", "wtf": "what the fuck", "xixixi": "tertawa", "ya": "iya", "yap": "iya", "yaudah": "ya sudah", "yawdah": "ya sudah", "yg": "yang", "yl": "yang lain", "yo": "iya", "yowes": "ya sudah", "yup": "iya", "7an": "tujuan", "ababil": "abg labil", "acc": "accord", "adlah": "adalah", "adoh": "aduh", "aha": "tertawa", "aing": "saya", "aja": "saja", "ajj": "saja", "aka": "dikenal juga sebagai", "akko": "aku", "akku": "aku", "akyu": "aku", "aljasa": "asal jadi saja", "ama": "sama", "ambl": "ambil", "anjir": "anjing", "ank": "anak", "ap": "apa", "apaan": "apa", "ape": "apa", "aplot": "unggah", "apva": "apa", "aqu": "aku", "asap": "sesegera mungkin", "aseek": "asyik", "asek": "asyik", "aseknya": "asyiknya", "asoy": "asyik", "astrojim": "astagfirullahaladzim", "ath": "kalau begitu", "atuh": "kalau begitu", "ava": "avatar", "aws": "awas", "ayang": "sayang", "ayok": "ayo", "bacot": "banyak bicara", "bales": "balas", "bangdes": "pembangunan desa", "bangkotan": "tua", "banpres": "bantuan presiden", "bansarkas": "bantuan sarana kesehatan", "bazis": "badan amal, zakat, infak, dan sedekah", "bcoz": "karena", "beb": "sayang", "bejibun": "banyak", "belom": "belum", "bener": "benar", "ber2": "berdua", "berdikari": "berdiri di atas kaki sendiri", "bet": "banget", "beti": "beda tipis", "beut": "banget", "bgd": "banget", "bgs": "bagus", "bhubu": "tidur", "bimbuluh": "bimbingan dan penyuluhan", "bisi": "kalau-kalau", "bkn": "bukan", "bl": "beli", "blg": "bilang", "blm": "belum", "bls": "balas", "bnchi": "benci", "bngung": "bingung", "bnyk": "banyak", "bohay": "badan aduhai", "bokep": "porno", "bokin": "pacar", "bole": "boleh", "bolot": "bodoh", "bonyok": "ayah ibu", "bpk": "bapak", "brb": "segera kembali", "brngkt": "berangkat", "brp": "berapa", "brur": "saudara laki-laki", "bsa": "bisa", "bsk": "besok", "bu_bu": "tidur", "bubarin": "bubarkan", "buber": "buka bersama", "bujubune": "luar biasa", "buser": "buru sergap", "bwhn": "bawahan", "byar": "bayar", "byr": "bayar", "c8": "chat", "cabut": "pergi", "caem": "cakep", "cama-cama": "sama-sama", "cangcut": "celana dalam", "cape": "capek", "caur": "jelek", "cekak": "tidak ada uang", "cekidot": "coba lihat", "cemplungin": "cemplungkan", "ceper": "pendek", "ceu": "kakak perempuan", "cewe": "cewek", "cibuk": "sibuk", "cin": "cinta", "ciye": "cie", "ckck": "ck", "clbk": "cinta lama bersemi kembali", "cmpr": "campur", "cnenk": "senang", "congor": "mulut", "cow": "cowok", "coz": "karena", "cpa": "siapa", "gokil": "gila", "gombal": "suka merayu", "gpl": "tidak pakai lama", "gpp": "tidak apa-apa", "gretong": "gratis", "gt": "begitu", "gtw": "tidak tahu", "gue": "saya", "guys": "teman-teman", "gws": "cepat sembuh", "haghaghag": "tertawa", "hakhak": "tertawa", "handak": "bahan peledak", "hansip": "pertahanan sipil", "hellow": "halo", "helow": "halo", "hi": "hai", "hlng": "hilang", "hnya": "hanya", "houm": "rumah", "hrs": "harus", "hubad": "hubungan angkatan darat", "hubla": "perhubungan laut", "huft": "mengeluh", "humas": "hubungan masyarakat", "idk": "saya tidak tahu", "ilfeel": "tidak suka", "imba": "jago sekali", "imoet": "imut", "info": "informasi", "itung": "hitung", "isengin": "bercanda", "iyala": "iya lah", "iyo": "iya", "jablay": "jarang dibelai", "jadul": "jaman dulu", "jancuk": "anjing", "jd": "jadi", "jdikan": "jadikan", "jg": "juga", "jgn": "jangan", "jijay": "jijik", "jkt": "jakarta", "jnj": "janji", "jth": "jatuh", "jurdil": "jujur adil", "jwb": "jawab", "ka": "kakak", "kabag": "kepala bagian", "kacian": "kasihan", "kadit": "kepala direktorat", "kaga": "tidak", "kaka": "kakak", "kamtib": "keamanan dan ketertiban", "kamuh": "kamu", "kamyu": "kamu", "kapt": "kapten", "kasat": "kepala satuan", "kasubbid": "kepala subbidang", "kau": "kamu", "kbar": "kabar", "kcian": "kasihan", "keburu": "terlanjur", "kedubes": "kedutaan besar", "kek": "seperti", "keknya": "kayaknya", "keliatan": "kelihatan", "keneh": "masih", "kepikiran": "terpikirkan", "kepo": "mau tahu urusan orang", "kere": "tidak punya uang", "kesian": "kasihan", "ketauan": "ketahuan", "keukeuh": "keras kepala", "khan": "kan", "kibus": "kaki busuk", "kk": "kakak", "klian": "kalian", "klo": "kalau", "kluarga": "keluarga", "klwrga": "keluarga", "kmari": "kemari", "kmpus": "kampus", "kn": "kan", "knl": "kenal", "knpa": "kenapa", "kog": "kok", "kompi": "komputer", "komtiong": "komunis Tiongkok", "konjen": "konsulat jenderal", "koq": "kok", "kpd": "kepada",
        "kptsan":"keputusan", "krik": "garing", "krn": "karena", "ktauan": "ketahuan", "ktny": "katanya", "kudu": "harus", "kuq": "kok", "ky": "seperti", "kykny": "kayanya", "laka": "kecelakaan",
        "lambreta": "lambat", "lansia": "lanjut usia", "lapas": "lembaga pemasyarakatan", "lbur": "libur", "lekong": "laki-laki", "lg": "lagi", "lgkp": "lengkap", "lht": "lihat",
        "linmas": "perlindungan masyarakat", "lmyan": "lumayan", "lngkp": "lengkap", "loch": "loh", "lol": "tertawa", "lom": "belum", "loupz": "cinta", "lowh": "kamu", "lu": "kamu",
        "luchu": "lucu", "luff": "cinta", "luph": "cinta", "lw": "kamu", "lwt": "lewat", "maaciw": "terima kasih", "mabes": "markas besar", "macem-macem": "macam-macam", "madesu": "masa depan suram",
        "maen": "main", "mahatma": "maju sehat bersama", "mak": "ibu", "makasih": "terima kasih", "malah": "bahkan", "malu2in": "memalukan", "mamz": "makan", "manies": "manis", "mantep": "mantap",
        "markus": "makelar kasus", "mba": "mbak", "mending": "lebih baik", "mgkn": "mungkin", "mhn": "mohon", "miker": "minuman keras", "milis": "mailing list", "mksd": "maksud", "mls": "malas",
        "mnt": "minta", "moge": "motor gede", "mokat": "mati", "mosok": "masa", "msh": "masih", "mskpn": "meskipun", "msng2": "masing-masing", "muahal": "mahal", "muker": "musyawarah kerja",
        "mumet": "pusing", "muna": "munafik", "munaslub": "musyawarah nasional luar biasa", "musda": "musyawarah daerah", "muup": "maaf", "muuv": "maaf", "nal": "kenal", "nangis": "menangis",
        "naon": "apa", "napol": "narapidana politik", "naq": "anak", "narsis": "bangga pada diri sendiri", "nax": "anak", "ndak": "tidak", "ndut": "gendut", "nekolim": "neokolonialisme",
        "nelfon": "menelepon", "ngabis2in": "menghabiskan", "ngakak": "tertawa", "ngambek": "marah", "ngampus": "pergi ke kampus", "ngantri": "mengantri", "ngapain": "sedang apa",
        "ngaruh": "berpengaruh", "ngawur": "berbicara sembarangan", "ngeceng": "kumpul bareng-bareng", "ngeh": "sadar", "ngekos": "tinggal di kos", "ngelamar": "melamar", "ngeliat": "melihat",
        "ngemeng": "bicara terus-terusan", "ngerti": "mengerti", "nggak": "tidak", "ngikut": "ikut", "nginep": "menginap", "ngisi": "mengisi", "ngmg": "bicara", "ngocol": "lucu",
        "ngomongin": "membicarakan", "ngumpul": "berkumpul", "ni": "ini", "nyasar": "tersesat", "nyariin": "mencari", "nyiapin": "mempersiapkan", "nyiram": "menyiram", "nyok": "ayo", "o/": "oleh",
        "ok": "ok", "priksa": "periksa", "pro": "profesional", "psn": "pesan", "psti": "pasti", "puanas": "panas", "qmo": "kamu", "qt": "kita", "rame": "ramai", "raskin": "rakyat miskin",
        "red": "redaksi", "reg": "register", "rejeki": "rezeki", "renstra": "rencana strategis", "reskrim": "reserse kriminal", "sni": "sini", "somse": "sombong sekali", "sorry": "maaf",
        "sosbud": "sosial-budaya", "sospol": "sosial-politik", "sowry": "maaf", "spd": "sepeda", "sprti": "seperti", "spy": "supaya", "stelah": "setelah", "subbag": "subbagian",
        "sumbangin": "sumbangkan", "sy": "saya", "syp": "siapa", "tabanas": "tabungan pembangunan nasional", "tar": "nanti", "taun": "tahun", "tawh": "tahu", "tdi": "tadi", "te2p": "tetap",
        "tekor": "rugi", "telkom": "telekomunikasi", "telp": "telepon", "temen2": "teman-teman", "tengok": "menjenguk", "terbitin": "terbitkan", "tgl": "tanggal", "thanks": "terima kasih",
        "thd": "terhadap", "thx": "terima kasih", "tipi": "TV", "tkg": "tukang", "tll": "terlalu", "tlpn": "telepon", "tman": "teman", "tmbh": "tambah", "tmn2": "teman-teman", "tmph": "tumpah",
        "tnda": "tanda", "tnh": "tanah", "togel": "toto gelap", "tp": "tapi", "tq": "terima kasih", "trgntg": "tergantung", "trims": "terima kasih", "cb": "coba", "y": "ya", "munfik": "munafik",
        "reklamuk": "reklamasi", "sma": "sama", "tren": "trend", "ngehe": "kesal", "mz": "mas", "analisise": "analisis", "sadaar": "sadar", "sept": "september", "nmenarik": "menarik",
        "zonk": "bodoh", "rights": "benar", "simiskin": "miskin", "ngumpet": "sembunyi", "hardcore": "keras", "akhirx": "akhirnya", "solve": "solusi", "watuk": "batuk", "ngebully": "intimidasi",
        "masy": "masyarakat", "still": "masih", "tauk": "tahu", "mbual": "bual", "tioghoa": "tionghoa", "ngentotin": "senggama", "kentot": "senggama", "faktakta": "fakta", "sohib": "teman",
        "rubahnn": "rubah", "trlalu": "terlalu", "nyela": "cela", "heters": "pembenci", "nyembah": "sembah", "most": "paling", "ikon": "lambang", "light": "terang", "pndukung": "pendukung",
        "setting": "atur", "seting": "akting", "next": "lanjut", "waspadalah": "waspada", "gantengsaya": "ganteng", "parte": "partai", "nyerang": "serang", "nipu": "tipu", "ktipu": "tipu",
        "jentelmen": "berani", "buangbuang": "buang", "tsangka": "tersangka", "kurng": "kurang", "ista": "nista", "less": "kurang", "koar": "teriak", "paranoid": "takut", "problem": "masalah",
        "tahi": "kotoran", "tirani": "tiran", "tilep": "tilap", "happy": "bahagia", "tak": "tidak", "penertiban": "tertib", "uasai": "kuasa", "mnolak": "tolak", "trending": "trend",
        "taik": "tahi", "wkwkkw": "tertawa", "ahokncc": "ahok", "istaa": "nista", "benarjujur": "jujur", "mgkin": "mungkin", 'ga':'tidak', 'cwe':'perempuan', 'dl':'dulu', 'rumayan':'lumayan',
        'ny':'nya', 'htm':'harga tiket masuk', 'cm':'cuma', 'slalu':'selalu', 'tingi':'tinggi','neng':'senang'}
processed_comments = []

for sentence in data['full_text']:
    # Remove all the special characters
    processed_comment = reg.sub(r'\W', ' ', str(sentence))

    # Converting to Lowercase
    processed_comment = processed_comment.lower()

    #Remove number
    processed_comment = reg.sub(r'\d+', ' ', processed_comment)

    # remove all single characters
    processed_comment = reg.sub(r'\s+[a-zA-Z]\s+', ' ', processed_comment)

    #remove duplicate character
    pattern=reg.compile(r"(.)\1{1,}",reg.DOTALL)
    processed_comment=pattern.sub(r"\1",processed_comment)


    #Corrected Slang words
    words = processed_comment.split()
    rfrm=[slangs[word] if word in slangs else word for word in words]
    processed_comment= " ".join(rfrm)

    #remove stopword
    factory = StopWordRemoverFactory()
    more_stopword = ['tak', 'jd', 'per', 'nya', 'terjemah', 'diterjemahkan', 'oleh', 'gogle', 'google' ,'nan', 'baik', 'sangat', 'batas', 'coba',
                        'ada','bersih', 'salur', 'baru', 'purwokerto', 'batas', 'hotel', 'coba', 'putus', 'ada','sama', 'suka', 'bilang',
                        'com', 'kamu', 'http', 'https', 'htps', 'htp', 'gak', 'jadi', 'lebih', 'kalau', 'banyak', 'jangan', 'iya', 'kok',
                        'apa', 'paling', 'semua', 'lah', 'ihwm', 'od', 'pakai', 'hayo', 'no', 'ihwjm', 'od'] #menambahkan stopword
    stopwords = factory.get_stop_words() + more_stopword
    temp = [t for t in reg.findall(r'\b[a-z]+-?[a-z]+\b',processed_comment) if t not in stopwords]
    processed_comment = ' '.join(temp)

    #stemming
    stemmer = StemmerFactory().create_stemmer()
    processed_comment = stemmer.stem(processed_comment)

    # Substituting multiple spaces with single space
    processed_comment = reg.sub(r'\s+', ' ', processed_comment, flags=reg.I)

    processed_comments.append(processed_comment)

#output data Preprocessing
processed_comments

['',
 'this anouncement doesn say anything about special guest and it doesn have photo that says it with jungkok like the last one think these are truly just listening parties to bost the song',
 'inspired by the golden moments of jungkok his solo album golden is coming pre save and pre order now the new album by the golden giant pop star coming out november rd pm kst golden by jungkok is coming',
 'inspired by the golden moments of jungkok his solo album golden is coming pre save and pre order now the new album by the golden giant pop star coming out november rd pm kst golden by jungkok is coming',
 'bts buter cardigan mini photocard phoca pc rm jin hope jimin jk jungkok md co fiom zpms',
 'drank litle to much wine and now im tipsy but just remembered have date with jungkok at am tmrw co nd xyvcxat',
 'golden is coming jungkok solo album golden by jungkok is coming goldenbyjk',
 'golden is coming jungkok solo album golden by jungkok is coming goldenbyjk',
 'dreamjeons signed up on wev

In [8]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [9]:
processed_comments = ''.join(processed_comments)

In [10]:
type(processed_comments)

str

In [11]:
from nltk.tokenize import word_tokenize
Docs = processed_comments
Sentences = nltk.sent_tokenize(Docs)
print ("Kalimat Awal: ", Sentences)
hasil_tokenizing = nltk.word_tokenize(Docs)
print("Setelah Tokenizing: ", hasil_tokenizing)

Kalimat Awal:  ['this anouncement doesn say anything about special guest and it doesn have photo that says it with jungkok like the last one think these are truly just listening parties to bost the songinspired by the golden moments of jungkok his solo album golden is coming pre save and pre order now the new album by the golden giant pop star coming out november rd pm kst golden by jungkok is cominginspired by the golden moments of jungkok his solo album golden is coming pre save and pre order now the new album by the golden giant pop star coming out november rd pm kst golden by jungkok is comingbts buter cardigan mini photocard phoca pc rm jin hope jimin jk jungkok md co fiom zpmsdrank litle to much wine and now im tipsy but just remembered have date with jungkok at am tmrw co nd xyvcxatgolden is coming jungkok solo album golden by jungkok is coming goldenbyjkgolden is coming jungkok solo album golden by jungkok is coming goldenbyjkdreamjeons signed up on weverse for jungkok golden a

In [12]:
len(hasil_tokenizing)

12559

In [13]:
#Ekstraksi fitur / representasi dokumen menggunakan TF
from sklearn.feature_extraction.text import CountVectorizer
tf_vectorizer = CountVectorizer(max_df=1.0, min_df=1)

tf = tf_vectorizer.fit_transform(hasil_tokenizing)

#hasil representasi
tf_terms = tf_vectorizer.get_feature_names_out()
print(tf_vectorizer.get_feature_names_out())
matrix = tf.toarray()
print(matrix)

['abangshould' 'ability' 'able' ... 'zrvpwhkgmhay' 'zscjtpkeq' 'zudlqx']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### **Menggunakan LDA**

In [14]:
from sklearn.decomposition import LatentDirichletAllocation as LDA

n_topics = 10 #untuk mendapatkan jumlah topik terbaik perlu trial
lda = LDA(n_components=n_topics, learning_method='batch', random_state=0)
lda.fit(tf)
lda

LatentDirichletAllocation(random_state=0)

In [15]:
vsm_topics = lda.transform(tf)
#tampilkan hasil
print(vsm_topics)

[[0.05       0.05       0.05       ... 0.05       0.05       0.55      ]
 [0.05       0.55       0.05       ... 0.05       0.05       0.05      ]
 [0.05       0.05       0.05       ... 0.05       0.05       0.05      ]
 ...
 [0.05       0.05       0.05       ... 0.54999999 0.05       0.05      ]
 [0.05       0.05       0.05       ... 0.05       0.05       0.05      ]
 [0.05       0.05       0.05       ... 0.05       0.05       0.05      ]]


In [16]:
len(vsm_topics)

12559

In [17]:
#Tampilkan nilai-nilai setiap fitur
print(lda.components_)

[[1.09999998 0.1        1.09999998 ... 0.1        0.1        0.1       ]
 [0.1        1.09999997 0.1        ... 0.1        0.1        0.1       ]
 [0.1        0.1        0.1        ... 0.1        0.1        0.1       ]
 ...
 [0.1        0.1        0.1        ... 0.1        0.1        0.1       ]
 [0.1        0.1        0.1        ... 0.1        1.09999997 0.1       ]
 [0.1        0.1        0.1        ... 0.1        0.1        0.1       ]]


In [18]:
#hasil label topic model untuk setiap dokumen
import numpy as np
topics = np.argmax(vsm_topics, axis=1)
topics

array([9, 1, 6, ..., 7, 3, 3])

In [19]:
#mencetak word fitur dengan nilai tertinggi pada setiap topik
n_top_words = 10 # jumlah fitur tertinggi yang kita tentukan
topic_words = {}
for topic, comp in enumerate(lda.components_):
 word_idx = np.argsort(comp)[::-1][:n_top_words] # susun indeks secara terbalik, sehingga yang paling tinggi muncul di awal.
 # store the words most relevant to the topic
 topic_words[topic] = [tf_vectorizer.get_feature_names_out()[i]+' '+str(comp[i]) for i in word_idx]

In [20]:
type(topic_words)

dict

In [21]:
topic_words

{0: ['is 349.09999998602297',
  'his 144.09999998599756',
  'rd 132.09999998599432',
  'kst 130.09999998599335',
  'el 47.09999998591712',
  'cominginspired 32.09999998586052',
  'amp 24.099999985801077',
  'that 18.099999985721254',
  'have 17.09999998570238',
  'ems 16.099999985681098'],
 1: ['golden 674.0999999796329',
  'the 471.0999999796179',
  'now 139.0999999795778',
  'out 134.09999997957627',
  'star 132.09999997957493',
  'bts 66.09999997951284',
  'me 42.09999997944153',
  'est 42.09999997944153',
  'stu 11.099999978876241',
  'del 11.099999978876241'],
 2: ['coming 323.0999999880826',
  'order 158.0999999880663',
  'for 51.09999998800221',
  'ver 47.0999999879941',
  'jk 20.099999987854453',
  'be 20.09999998785445',
  'live 15.099999987772335',
  'las 13.099999987721397',
  'or 11.09999998765145',
  'stationhead 11.099999987651449'],
 3: ['jungkok 602.0999999842757',
  'new 132.09999998424328',
  'pm 131.09999998424337',
  'moments 129.09999998424271',
  'rasa 42.09999998

In [22]:
for topic, words in topic_words.items():
 print('Topic: %d' % topic)
 print(' %s' % ', '.join(words))

Topic: 0
 is 349.09999998602297, his 144.09999998599756, rd 132.09999998599432, kst 130.09999998599335, el 47.09999998591712, cominginspired 32.09999998586052, amp 24.099999985801077, that 18.099999985721254, have 17.09999998570238, ems 16.099999985681098
Topic: 1
 golden 674.0999999796329, the 471.0999999796179, now 139.0999999795778, out 134.09999997957627, star 132.09999997957493, bts 66.09999997951284, me 42.09999997944153, est 42.09999997944153, stu 11.099999978876241, del 11.099999978876241
Topic: 2
 coming 323.0999999880826, order 158.0999999880663, for 51.09999998800221, ver 47.0999999879941, jk 20.099999987854453, be 20.09999998785445, live 15.099999987772335, las 13.099999987721397, or 11.09999998765145, stationhead 11.099999987651449
Topic: 3
 jungkok 602.0999999842757, new 132.09999998424328, pm 131.09999998424337, moments 129.09999998424271, rasa 42.099999984140574, so 36.099999984115314, xylitol 28.099999984064496, po 25.099999984036952, with 22.09999998400179, con 21.099

**Interpretasi hasil :**

**Misal topic 0, didalamnya terdapat kata is, his, rd, kst, el, dsb dengan probabilitas masing - masing. Di mana kita dapat melihat bahwa kata is memiliki nilai 349.09. Artinya bahwa kata "is" dalam topik tersebut memiliki distrusi probalitas paling tinggi.**

### **Menggunakan LSA**

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
vektor = TfidfVectorizer(max_features=400)

In [24]:
df = pd.read_csv('Jungkook.csv')

In [25]:
df.head()

Unnamed: 0                      created_at               id_str  \
0           0  Wed Oct 04 03:23:42 +0000 2023  1709408926565826963   
1           1  Wed Oct 04 03:23:42 +0000 2023  1709408926435889254   
2           2  Wed Oct 04 03:23:40 +0000 2023  1709408921524281824   
3           3  Wed Oct 04 03:23:40 +0000 2023  1709408921104908629   
4           4  Wed Oct 04 03:23:40 +0000 2023  1709408920123683144   

                                           full_text  quote_count  \
0                                #JungKook_GOLDEN 👇👇            0   
1  This announcement doesn’t say anything about a...            0   
2  Inspired by the golden moments of #JungKook, h...            0   
3  Inspired by the golden moments of #JungKook, h...            0   
4  방탄소년단 방탄 버터 가디건 포카 양도 bts butter cardigan mini...            0   

   reply_count  retweet_count  favorite_count lang          user_id_str  \
0            0              0               0  qme  1674311398770331649   
1            0              0               0   en            346247756   
2            0              0               0   en  1146317892352393216   
3            0              0               0   en  1587683842625781760   
4            0              0               0   ko  1310575995296968706   

   conversation_id_str      username  \
0  1709408926565826963     racesar86   
1  1709408926435889254   laurayjames   
2  1709408921524281824  Min_myyoongi   
3  1709408921104908629     Andythv16   
4  1709408920123683144       _derfun   

                                           tweet_url  
0  https://twitter.com/racesar86/status/170940892...  
1  https://twitter.com/laurayjames/status/1709408...  
2  https://twitter.com/Min_myyoongi/status/170940...  
3  https://twitter.com/Andythv16/status/170940892...  
4  https://twitter.com/_derfun/status/17094089201...

In [26]:
df = df['full_text']

In [27]:
df = pd.DataFrame(df)

In [28]:
df.head()

full_text
0                                #JungKook_GOLDEN 👇👇
1  This announcement doesn’t say anything about a...
2  Inspired by the golden moments of #JungKook, h...
3  Inspired by the golden moments of #JungKook, h...
4  방탄소년단 방탄 버터 가디건 포카 양도 bts butter cardigan mini...

In [29]:
#menghitung tf-idf dengan TfidfTransformer
vektor_dt=vektor.fit_transform(df['full_text'].values.astype('U'))
print (vektor_dt)
print (vektor_dt.shape)

  (0, 171)	1.0
  (1, 290)	0.24880749992040554
  (1, 319)	0.1599302330861236
  (1, 187)	0.25485142252629095
  (1, 173)	0.23045526315699844
  (1, 43)	0.22347806655769126
  (1, 231)	0.23870753520321114
  (1, 312)	0.21087158639027384
  (1, 186)	0.22347806655769126
  (1, 169)	0.05891812793835312
  (1, 360)	0.20100824833281278
  (1, 311)	0.21210302639359133
  (1, 142)	0.2146901410992338
  (1, 159)	0.3842094211781831
  (1, 41)	0.10994072015986994
  (1, 292)	0.2618286191255981
  (1, 26)	0.22347806655769126
  (1, 42)	0.25485142252629095
  (1, 271)	0.27008089117181083
  (1, 317)	0.20512582979428412
  (2, 179)	0.13217245317085524
  (2, 11)	0.13217245317085524
  (2, 20)	0.13217245317085524
  (2, 224)	0.13033966569908154
  (2, 237)	0.13070077216944584
  :	:
  (713, 273)	0.6176929086246765
  (713, 275)	0.6371612537582619
  (713, 232)	0.2636091069930398
  (713, 75)	0.11123344150475804
  (713, 149)	0.111453607322724
  (713, 399)	0.25992556825663293
  (713, 34)	0.21402135498711194
  (713, 169)	0.069498

In [30]:
# topic modeling using LSA
from sklearn.decomposition import TruncatedSVD
lsa_model = TruncatedSVD(n_components=5, n_iter=10, random_state=42)

lsa_top=lsa_model.fit_transform(vektor_dt)
print(lsa_top)

[[ 0.14465356  0.26529895 -0.60592495 -0.46799927 -0.49998212]
 [ 0.10226278  0.05280024  0.0016908   0.08483551  0.05467641]
 [ 0.990713   -0.08935521  0.03982456 -0.04034218  0.0492801 ]
 ...
 [ 0.03863553  0.27404647 -0.0500248   0.1279869   0.10786427]
 [ 0.19149988  0.31454389  0.03473359  0.63961924 -0.43348463]
 [ 0.12807024  0.29936246 -0.14213118  0.05559805 -0.05364207]]


In [31]:
len(lsa_top)

717

In [32]:
lsa_model.get_params()

{'algorithm': 'randomized',
 'n_components': 5,
 'n_iter': 10,
 'n_oversamples': 10,
 'power_iteration_normalizer': 'auto',
 'random_state': 42,
 'tol': 0.0}

In [33]:
# Memunculkan nilai lsa setiap topik
l=lsa_top[0]
print("Topik- Topik:")
for i,topic in enumerate(l):
  print("Topic ",i," : ",topic*100)

Topik- Topik:
Topic  0  :  14.465355726370488
Topic  1  :  26.52989479563579
Topic  2  :  -60.59249511173618
Topic  3  :  -46.79992699805632
Topic  4  :  -49.99821159914404


In [34]:
# Memunculkan jumlah kata-kata dalam setiap topik
print(lsa_model.components_.shape)
print(lsa_model.components_)

(5, 400)
[[ 0.00113542  0.00116164  0.00175317 ...  0.00180275  0.00180275
   0.00677111]
 [ 0.00670117  0.00652341  0.01849782 ...  0.12024669  0.12024669
   0.05651562]
 [-0.00367943 -0.00178049 -0.00357358 ...  0.22034709  0.22034709
  -0.04746391]
 [ 0.00066557  0.00580704  0.01207578 ... -0.10881123 -0.10881123
   0.00913752]
 [ 0.00517642  0.0088676   0.01950038 ... -0.09243465 -0.09243465
  -0.02233595]]


In [35]:
# Word/ kata paling penting dalam setiap topik
vocab = vektor.get_feature_names_out()
for i, comp in enumerate(lsa_model.components_):
    vocab_comp = zip(vocab, comp)
    sorted_words = sorted(vocab_comp, key= lambda x:x[1], reverse=True)[:10]
    print("Topic "+str(i)+": ")
    for t in sorted_words:
        print(t[0],end=", ")
    print("\n")

Topic 0: 
golden, coming, by, the, is, pre, album, jungkook, jungkook_golden, solo, 

Topic 1: 
co, https, jungkook, jungkook_golden, bts, bts_xylitol, gum__lotte, smile2smile, xylitol, だと思う, 

Topic 2: 
bts_xylitol, gum__lotte, smile2smile, xylitol, だと思う, キシリトール, フーセンガム, 大切な歯のために, 新発売, 本当にキシリトールガムを噛んでいるのは, 

Topic 3: 
jungkook, de, album, el, que, me, en, álbum, no, to, 

Topic 4: 
co, https, the, pre, order, dp, and, now, of, jungkook_3d, 



In [36]:
for topic, words in topic_words.items():
 print('Topic: %d' % topic)
 print(' %s' % ', '.join(words))

Topic: 0
 is 349.09999998602297, his 144.09999998599756, rd 132.09999998599432, kst 130.09999998599335, el 47.09999998591712, cominginspired 32.09999998586052, amp 24.099999985801077, that 18.099999985721254, have 17.09999998570238, ems 16.099999985681098
Topic: 1
 golden 674.0999999796329, the 471.0999999796179, now 139.0999999795778, out 134.09999997957627, star 132.09999997957493, bts 66.09999997951284, me 42.09999997944153, est 42.09999997944153, stu 11.099999978876241, del 11.099999978876241
Topic: 2
 coming 323.0999999880826, order 158.0999999880663, for 51.09999998800221, ver 47.0999999879941, jk 20.099999987854453, be 20.09999998785445, live 15.099999987772335, las 13.099999987721397, or 11.09999998765145, stationhead 11.099999987651449
Topic: 3
 jungkok 602.0999999842757, new 132.09999998424328, pm 131.09999998424337, moments 129.09999998424271, rasa 42.099999984140574, so 36.099999984115314, xylitol 28.099999984064496, po 25.099999984036952, with 22.09999998400179, con 21.099

**Interpretasi hasil :**

**Misal topic 0, didalamnya terdapat kata is, his, rd, kst, el, dsb dengan probabilitas masing - masing. Di mana kita dapat melihat bahwa kata is memiliki nilai 349.09. Artinya bahwa kata "is" dalam topik tersebut memiliki distrusi probalitas paling tinggi.**